INSERT INTO hobby (nome, descricao) VALUES
('Leitura', 'Apreciar livros, revistas ou quadrinhos para entretenimento ou aprendizado.'),
('Escrita', 'Produzir textos como contos, poesias, blogs ou diários pessoais.'),
('Desenho', 'Criar imagens artísticas à mão com lápis, caneta ou carvão.'),
('Pintura', 'Utilizar tintas para expressar criatividade em telas ou outras superfícies.'),
('Fotografia', 'Capturar momentos e paisagens por meio de câmeras digitais ou analógicas.'),
('Jardinagem', 'Cuidar de plantas, flores e hortas para relaxamento e conexão com a natureza.'),
('Culinária', 'Preparar receitas variadas como forma de lazer e descoberta de sabores.'),
('Costura', 'Criar ou reparar roupas e acessórios usando agulha e linha.'),
('Artesanato', 'Produzir objetos manuais decorativos ou funcionais com diferentes materiais.'),
('Colecionismo', 'Juntar e organizar itens como moedas, selos, quadrinhos ou action figures.'),
('Tocar Instrumento', 'Aprender e praticar instrumentos como violão, teclado ou bateria.'),
('Cantar', 'Praticar canto como forma de expressão artística e emocional.'),
('Dança', 'Movimentar-se com ritmo, seja por lazer ou como atividade física.'),
('Meditação', 'Praticar técnicas de atenção plena para reduzir o estresse e melhorar o foco.'),
('Yoga', 'Realizar posturas e exercícios de respiração para bem-estar físico e mental.'),
('Caminhada', 'Caminhar em ritmo leve ou moderado como forma de lazer e exercício.'),
('Corrida', 'Praticar corrida para manter a saúde e desafiar seus limites físicos.'),
('Andar de Bicicleta', 'Pedalar em trilhas, ruas ou parques por lazer ou exercício.'),
('Natação', 'Nadar em piscinas ou em águas naturais como forma de recreação e saúde.'),
('Esportes em Equipe', 'Participar de jogos coletivos como futebol, vôlei ou basquete.'),
('Video Game', 'Jogar jogos digitais em consoles ou computadores para entretenimento.'),
('RPG de Mesa', 'Participar de jogos de interpretação de personagens com dados e narrativa.'),
('Modelismo', 'Montar e pintar miniaturas de aviões, carros, trens ou cenários.'),
('Programação', 'Criar aplicativos, jogos ou sistemas por diversão ou aprendizado.'),
('Aprender Idiomas', 'Estudar novas línguas como forma de se comunicar e expandir horizontes.'),
('Assistir Filmes e Séries', 'Apreciar produções cinematográficas como forma de lazer.'),
('Pesca', 'Atividade relaxante praticada em rios, lagos ou no mar.'),
('Acampamento', 'Passar tempo na natureza, geralmente dormindo em barracas ou cabanas.'),
('Astronomia', 'Observar estrelas, planetas e fenômenos celestes com telescópios ou a olho nu.'),
('Voluntariado', 'Participar de ações sociais e comunitárias como forma de ajudar os outros.');
