-- Deleta todas as mídias do usuário de teste (id = 3)

SET client_encoding = 'UTF8';
DELETE FROM midia
WHERE cadastro_id = 3;

-- Reinseri a mídia de teste

INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1994, NULL, '2025-08-19 10:45:27.320', 1, 3, 2, 142, 8.713, 'Castle Rock Entertainment', '', '', 'HD', '', '', 'en', 'Um Sonho de Liberdade', 'The Shawshank Redemption', 'Blu-ray', 'Filme', 'Roger Deakins, Frank Darabont', 'Em 1946, Andy Dufresne, um banqueiro jovem e bem sucedido, tem a sua vida radicalmente modificada ao ser condenado por um crime que nunca cometeu, o homicídio de sua esposa e do amante dela. Ele é mandado para uma prisão que é o pesadelo de qualquer detento, a Penitenciária Estadual de Shawshank, no Maine. Lá ele irá cumprir a pena perpétua. Andy logo será apresentado a Warden Norton, o corrupto e cruel agente penitenciário, que usa a Bíblia como arma de controle e ao Capitão Byron Hadley que trata os internos como animais. Andy faz amizade com Ellis Boyd Redding, um prisioneiro que cumpre pena há 20 anos e controla o mercado negro da instituição.', 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler, Clancy Brown', 'Drama, Crime', 'https://image.tmdb.org/t/p/w500/xSnM4ahmz692msbMTBsfBWHvR3M.jpg', '16', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1972, NULL, '2025-08-19 10:45:54.671', 1, 3, 2, 175, 8.687, 'Paramount Pictures', '', '', 'HD', '', '', 'en', 'O Poderoso Chefão', 'The Godfather', 'Blu-ray', 'Filme', 'Gordon Willis, Francis Ford Coppola', 'Em 1945, Don Corleone é o chefe de uma mafiosa família italiana de Nova York. Ele costuma apadrinhar várias pessoas, realizando importantes favores para elas, em troca de favores futuros. Com a chegada das drogas, as famílias começam uma disputa pelo promissor mercado. Quando Corleone se recusa a facilitar a entrada dos narcóticos na cidade, não oferecendo ajuda política e policial, sua família começa a sofrer atentados para que mudem de posição. É nessa complicada época que Michael, um herói de guerra nunca envolvido nos negócios da família, vê a necessidade de proteger o seu pai e tudo o que ele construiu ao longo dos anos.', 'Marlon Brando, Al Pacino, James Caan, Robert Duvall, Richard S. Castellano', 'Drama, Crime', 'https://image.tmdb.org/t/p/w500/uP46DujkD3nwcisOjz9a0Xw0Knj.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1985, NULL, '2025-08-21 17:03:44.368', 1, 3, 6, 91, 7.2, 'Hemdale Film Corporation', '', '', 'HD', '', '', 'en', 'A Volta dos Mortos Vivos', 'The Return of the Living Dead', VHS, 'Filme', 'Dan O''Bannon, Jules Brenner', 'Dois empregados de um armazém de medicamentos encontram no subsolo do estabelecimento barris do exército, lacrados e acidentalmente liberam um gás mortal no ar. Esse gás acaba re-animando os Mortos de um cemitério próximo, que vão querer apenas uma coisa dos vivos: seus miolos.', 'Clu Gulager, James Karen, Don Calfa, Thom Mathews, Miguel A. Núñez Jr.', 'Terror, Comédia, Ficção científica', 'https://image.tmdb.org/t/p/w500/6DGsNitU2bO1n94GNwEeGX4PLMG.jpg', '16', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1974, NULL, '2025-08-19 10:46:27.529', 1, 3, 2, 202, 8.571, 'Paramount Pictures', '', '', 'HD', '', '', 'en', 'O Poderoso Chefão: Parte II', 'The Godfather Part II', 'Blu-ray', 'Filme', 'Gordon Willis, Francis Ford Coppola', 'Após a máfia matar sua família, o jovem Vito foge da sua cidade na Sicília e vai para a América. Vito luta para manter sua família. Ele mata Black Hand Fanucci, que exigia dos comerciantes uma parte dos seus ganhos. Com a morte de Fanucci, o poderio de Vito cresce, mas sua família é o que mais importa para ele. Agora baseado no Lago Tahoe, Michael planeja fazer incursões em Las Vegas e Havana instalando negócios ligados ao lazer, mas descobre que aliados como Hyman Roth estão tentando matá-lo.', 'Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro, John Cazale', 'Drama, Crime', 'https://image.tmdb.org/t/p/w500/7g6wvsWHxBQujUcSXvZLhdFpDUy.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2008, NULL, '2025-08-19 10:48:58.461', 1, 3, 2, 152, 8.522, 'Warner Bros. Pictures', '', '', 'HD', '', '', 'en', 'Batman: O Cavaleiro das Trevas', 'The Dark Knight', 'Blu-ray', 'Filme', 'Wally Pfister, Christopher Nolan', 'Após dois anos desde o surgimento do Batman, os criminosos de Gotham City têm muito o que temer. Com a ajuda do tenente James Gordon e do promotor público Harvey Dent, Batman luta contra o crime organizado. Acuados com o combate, os chefes do crime aceitam a proposta feita pelo Coringa e o contratam para combater o Homem-Morcego.', 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Maggie Gyllenhaal', 'Drama, Ação, Crime, Thriller', 'https://image.tmdb.org/t/p/w500/4lj1ikfsSmMZNyfdi8R8Tv5tsgb.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1957, NULL, '2025-08-19 10:49:31.895', 1, 3, 1, 96, 8.549, 'United Artists', '', '', 'HD', '', '', 'en', '12 Homens e uma Sentença', '12 Angry Men', 'DVD', 'Filme', 'Boris Kaufman, Sidney Lumet', 'Um jovem porto-riquenho é acusado do brutal crime de ter matado o próprio pai. Quando ele vai a julgamento, doze jurados se reúnem para decidir a sentença, levando em conta que o réu deve ser considerado inocente até que se prove o contrário. Onze dos jurados têm plena certeza de que ele é culpado, e votam pela condenação, mas um jurado acha que é melhor investigar mais para que a sentença seja correta. Para isso ele terá que enfrentar diferentes interpretações dos fatos, e a má vontade dos outros jurados, que só querem ir logo para suas casas.', 'Martin Balsam, John Fiedler, Lee J. Cobb, E.G. Marshall, Jack Klugman', 'Drama', 'https://image.tmdb.org/t/p/w500/q8RGf4SbVCObCySZ4PIGsn5wFm6.jpg', '', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1993, NULL, '2025-08-19 10:49:55.551', 1, 3, 2, 195, 8.566, 'Amblin Entertainment', '', '', 'HD', '', '', 'en', 'A Lista de Schindler', 'Schindler''s List', 'Blu-ray', 'Filme', 'Steven Spielberg, Janusz Kamiński', 'O alemão Oskar Schindler viu na mão de obra judia uma solução barata e viável para lucrar com negócios durante a guerra. Com sua forte influência dentro do partido nazista, foi fácil conseguir as autorizações e abrir uma fábrica. O que poderia parecer uma atitude de um homem não muito bondoso, transformou-se em um dos maiores casos de amor à vida da História, pois este alemão abdicou de toda sua fortuna para salvar a vida de mais de mil judeus em plena luta contra o extermínio alemão.', 'Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall, Jonathan Sagall', 'Drama, História, Guerra', 'https://image.tmdb.org/t/p/w500/fvPYwfXH513e8Nqe0kzWFm2jjg.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2003, NULL, '2025-08-19 10:50:20.711', 1, 3, 2, 202, 8.488, 'New Line Cinema', '', '', 'HD', '', '', 'en', 'O Senhor dos Anéis: O Retorno do Rei', 'The Lord of the Rings: The Return of the King', 'Blu-ray', 'Filme', 'Andrew Lesnie, Peter Jackson', 'O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima. Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência. Um exército é reunido por Theoden em Rohan, em mais uma tentativa de deter as forças de Sauron. Enquanto isso, Frodo, Sam e Gollum seguem sua viagem rumo à Montanha da Perdição para destruir o anel.', 'Elijah Wood, Ian McKellen, Viggo Mortensen, Sean Astin, Andy Serkis', 'Aventura, Fantasia, Ação', 'https://image.tmdb.org/t/p/w500/egSO4klmc9pnI1CNnHoYKV70XKI.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1994, NULL, '2025-08-19 10:50:39.325', 1, 3, 1, 154, 8.5, 'Miramax', '', '', 'HD', '', '', 'en', 'Pulp Fiction: Tempo de Violência', 'Pulp Fiction', 'DVD', 'Filme', 'Andrzej Sekuła, Quentin Tarantino', 'Vincent Vega e Jules Winnfield são dois assassinos profissionais que trabalham fazendo cobranças para Marsellus Wallace, um poderosos gângster. Vega é forçado a sair com a garota do chefe, temendo passar dos limites. Enquanto isso, o pugilista Butch Coolidge se mete em apuros por ganhar uma luta que deveria perder.', 'John Travolta, Samuel L. Jackson, Uma Thurman, Bruce Willis, Ving Rhames', 'Thriller, Crime, Comédia, Drama', 'https://image.tmdb.org/t/p/w500/tptjnB2LDbuUWya9Cx5sQtv5hqb.jpg', '18', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2001, NULL, '2025-08-19 10:51:14.215', 1, 3, 2, 179, 8.4, 'New Line Cinema', '', '', 'HD', '', '', 'en', 'O Senhor dos Anéis: A Sociedade do Anel', 'The Lord of the Rings: The Fellowship of the Ring', 'Blu-ray', 'Filme', 'Peter Jackson, Andrew Lesnie', 'Em uma terra fantástica e única, um hobbit recebe de presente de seu tio um anel mágico e maligno que precisa ser destruído antes que caia nas mãos do mal. Para isso, o hobbit Frodo tem um caminho árduo pela frente, onde encontra perigo, medo e seres bizarros. Ao seu lado para o cumprimento desta jornada, ele aos poucos pode contar com outros hobbits, um elfo, um anão, dois humanos e um mago, totalizando nove pessoas que formam a Sociedade do Anel.', 'Elijah Wood, Ian McKellen, Viggo Mortensen, Sean Astin, Ian Holm', 'Aventura, Fantasia, Ação', 'https://image.tmdb.org/t/p/w500/omoMXT3Z7XrQwRZ2OGJGNWbdeEl.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1966, NULL, '2025-08-19 10:51:40.361', 1, 3, 6, 163, 8.465, 'United Artists', '', '', 'HD', '', '', 'it', 'Três Homens em Conflito', 'Il buono, il brutto, il cattivo', 'VHS', 'Filme', 'Sergio Leone, Tonino Delli Colli', 'Durante o auge da Guerra Civil, um misterioso pistoleiro vaga pela fronteira do oeste. Ele não possui um lar, lealdade ou companhia... Até que encontra dois estrangeiros, que são tão brutos e desapegados quanto ele. Unidos pelo destino, os três homens juntam suas forças para tentar encontrar uma fortuna em ouro roubado. Mas trabalho em equipe não é uma coisa natural para voluntariosos pistoleiros, e eles logo descobrem que seu maior desafio é concentrar-se em sua perigosa missão — e em manterem-se vivos — atravessando um país arrasado pela guerra.', 'Clint Eastwood, Eli Wallach, Lee Van Cleef, Aldo Giuffrè, Luigi Pistilli', 'Faroeste', 'https://image.tmdb.org/t/p/w500/bHwIzQrbJKiFwArLLngS1Ej6xPc.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1999, NULL, '2025-08-19 10:52:05.223', 1, 3, 2, 139, 8.437, 'Fox 2000 Pictures', '', '', 'HD', '', '', 'en', 'Clube da Luta', 'Fight Club', 'Blu-ray', 'Filme', 'Jeff Cronenweth, David Fincher', 'Um homem deprimido que sofre de insônia conhece um estranho vendedor de sabonetes chamado Tyler Durden. Eles formam um clube clandestino com regras rígidas onde lutam com outros homens cansados de suas vidas mundanas. Mas sua parceria perfeita é comprometida quando Marla chama a atenção de Tyler.', 'Edward Norton, Brad Pitt, Helena Bonham Carter, Meat Loaf, Jared Leto', 'Drama, Thriller', 'https://image.tmdb.org/t/p/w500/r3pPehX4ik8NLYPpbDRAh0YRtMb.jpg', '18', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1994, NULL, '2025-08-19 10:52:29.693', 1, 3, 2, 142, 8.466, 'Paramount Pictures', '', '', 'HD', '', '', 'en', 'Forrest Gump: O Contador de Histórias', 'Forrest Gump', 'Blu-ray', 'Filme', 'Robert Zemeckis, Don Burgess', 'Quarenta anos da história dos Estados Unidos, vistos pelos olhos de Forrest Gump, um rapaz com QI abaixo da média e com boas intenções. Por obra do acaso, ele consegue participar de momentos cruciais, como a Guerra do Vietnã e o Caso Watergate, mas continua pensando no seu amor de infância, Jenny Curran.', 'Tom Hanks, Robin Wright, Gary Sinise, Sally Field, Mykelti Williamson', 'Comédia, Drama, Romance', 'https://image.tmdb.org/t/p/w500/d74WpIsH8379TIL4wUxDneRCYv2.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2010, NULL, '2025-08-19 10:53:57.792', 1, 3, 2, 148, 8.369, 'Legendary Pictures', '', '', 'HD', '', '', 'en', 'A Origem', 'Inception', 'Blu-ray', 'Filme', 'Wally Pfister, Christopher Nolan', 'Cobb é um ladrão habilidoso que comete espionagem corporativa infiltrando-se no subconsciente de seus alvos durante o estado de sono. Impedido de retornar para sua família, ele recebe a oportunidade de se redimir ao realizar uma tarefa aparentemente impossível: plantar uma ideia na mente do herdeiro de um império. Para realizar o crime perfeito, ele conta com a ajuda do parceiro Arthur, o discreto Eames e a arquiteta de sonhos Ariadne. Juntos, eles correm para que o inimigo não antecipe seus passos.', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ken Watanabe, Tom Hardy, Elliot Page', 'Ação, Ficção científica, Aventura', 'https://image.tmdb.org/t/p/w500/9e3Dz7aCANy5aRUQF745IlNloJ1.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2002, NULL, '2025-08-19 10:54:19.912', 1, 3, 2, 180, 8.4, 'New Line Cinema', '', '', 'HD', '', '', 'en', 'O Senhor dos Anéis: As Duas Torres', 'The Lord of the Rings: The Two Towers', 'Blu-ray', 'Filme', 'Andrew Lesnie, Peter Jackson', 'Após a captura de Merry e Pippy pelos orcs, a Sociedade do Anel é dissolvida. Frodo e Sam seguem sua jornada rumo à Montanha da Perdição para destruir o anel e descobrem que estão sendo perseguidos pelo misterioso Gollum. Enquanto isso, Aragorn, o elfo e arqueiro Legolas e o anão Gimli partem para resgatar os hobbits sequestrados e chegam ao reino de Rohan, onde o rei Theoden foi vítima de uma maldição mortal de Saruman.', 'Elijah Wood, Ian McKellen, Viggo Mortensen, Sean Astin, Andy Serkis', 'Aventura, Fantasia, Ação', 'https://image.tmdb.org/t/p/w500/cmTFY35KK40yBX23Z9HhqU5uZ2O.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1975, NULL, '2025-08-19 10:54:45.602', 1, 3, 6, 133, 8.414, 'Fantasy Films', '', '', 'HD', '', '', 'en', 'Um Estranho no Ninho', 'One Flew Over the Cuckoo''s Nest', 'VHS', 'Filme', 'Miloš Forman, Haskell Wexler', 'Randle Patrick McMurphy é um malandro que, após ser preso, se finge de louco para ir a um hospital psiquiátrico e assim esquivar-se a uma porção de trabalhos forçados na prisão. Lá ele começa a influenciar os outros internos e começa a sofrer oposição da cruel e sádica enfermeira Mildred Ratched. Com forte poder persuasivo, McMurphy instaura uma reviravolta na clínica, não sabendo o que isto pode lhe custar.', 'Jack Nicholson, Brad Dourif, Louise Fletcher, Danny DeVito, William Redfield', 'Drama', 'https://image.tmdb.org/t/p/w500/nqz0NHRmbc57HZdZxi66shMzGKO.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1999, NULL, '2025-08-19 10:55:10.560', 1, 3, 2, 136, 8.23, 'Village Roadshow Pictures', '', '', 'HD', '', '', 'en', 'Matrix', 'The Matrix', 'Blu-ray', 'Filme', 'Bill Pope, Lana Wachowski, Lilly Wachowski', 'Thomas Anderson, um jovem programador de computador que mora em um cubículo escuro, é atormentado por estranhos pesadelos nos quais encontra-se conectado por cabos e contra sua vontade, em um imenso sistema de computadores do futuro. Em todas essas ocasiões, acorda gritando no exato momento em que os eletrodos estão para penetrar em seu cérebro. À medida que o sonho se repete, Anderson começa a ter dúvidas sobre a realidade. Por meio do encontro com os misteriosos Morpheus e Trinity, Thomas descobre que é, assim como outras pessoas, vítima da Matrix, um sistema inteligente e artificial que manipula a mente das pessoas, criando a ilusão de um mundo real enquanto usa os cérebros e corpos dos indivíduos para produzir energia. Morpheus, entretanto, está convencido de que Thomas é Neo, o aguardado messias capaz de enfrentar a Matrix e conduzir as pessoas de volta à realidade e à liberdade.', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, Gloria Foster', 'Ação, Ficção científica', 'https://image.tmdb.org/t/p/w500/lDqMDI3xpbB9UQRyeXfei0MXhqb.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1990, NULL, '2025-08-19 10:55:34.083', 1, 3, 1, 146, 8.454, 'Winkler Films', '', '', 'HD', '', '', 'en', 'Os Bons Companheiros', 'GoodFellas', 'DVD', 'Filme', 'Martin Scorsese, Michael Ballhaus', 'A história real de Henry Hill, um garoto meio irlandês e meio siciliano do Brooklyn que é adotado por gangsters do bairro ainda jovem e sobe na hierarquia de uma família da máfia sob a orientação de Jimmy Conway.', 'Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco, Paul Sorvino', 'Drama, Crime', 'https://image.tmdb.org/t/p/w500/lanYBnyCcqkaFqz66B8PrBRCtCW.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1980, NULL, '2025-08-19 10:58:32.173', 1, 3, 1, 124, 8.395, 'Lucasfilm Ltd.', '', '', 'HD', '', '', 'en', 'Guerra nas Estrelas: O Império Contra-Ataca', 'The Empire Strikes Back', 'DVD', 'Filme', 'Irvin Kershner, Peter Suschitzky', 'As forças imperais comandadas por Darth Vader lançam um ataque contra os membros da resistência, que são obrigados a fugir. Enquanto isso Luke Skywalker tenta encontrar o Mestre Yoda, que poderá ensiná-lo a dominar a "Força" e torná-lo um cavaleiro jedi. No entanto, Darth Vader planeja levá-lo para o lado negro da "Força".', 'Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams, Anthony Daniels', 'Aventura, Ação, Ficção científica', 'https://image.tmdb.org/t/p/w500/dLGT8b4Ut10z44uYLaip4QiwKta.jpg', 'L', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1954, NULL, '2025-08-19 10:58:56.413', 1, 3, 6, 207, 8.456, 'TOHO', '', '', 'HD', '', '', 'ja', 'Os Sete Samurais', '七人の侍', 'VHS', 'Filme', 'Akira Kurosawa, 中井朝一', 'Um bando de bandidos aterroriza os habitantes de uma pequena cidade, saqueando-os periodicamente sem piedade. Para repelir estes ataques, os aldeões decidem contratar mercenários. Por fim, obtêm os serviços de 7 guerreiros, 7 samurais dispostos a defendê-los em troca apenas de abrigo e comida.', 'Toshirô Mifune, 志村喬, 稲葉義男, 宮口精二, 千秋実', 'Ação, Drama', 'https://image.tmdb.org/t/p/w500/telXEMxGtJvffm5JDsx1rQzwWlf.jpg', '10', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1997, NULL, '2025-08-19 10:59:44.651', 1, 3, 1, 116, 8.442, 'Mario e Vittorio Cecchi Gori - C.E.I.A.D.', '', '', 'HD', '', '', 'it', 'A Vida é Bela', 'La vita è bella', 'DVD', 'Filme', 'Roberto Benigni, Tonino Delli Colli', 'Durante a Segunda Guerra Mundial na Itália, o judeu Guido e seu filho Giosué são levados para um campo de concentração nazista. Afastado da mulher, ele tem que usar sua imaginação para fazer o menino acreditar que estão participando de uma grande brincadeira, com o intuito de protegê-lo do terror e da violência que os cercam.', 'Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini, Giustino Durano, Sergio Bini Bustric', 'Comédia, Drama', 'https://image.tmdb.org/t/p/w500/mdqU2CHabmbdkWKs1IvCfksbtNM.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1991, NULL, '2025-08-19 11:00:09.517', 1, 3, 1, 118, 8.346, 'Orion Pictures', '', '', 'HD', '', '', 'en', 'O Silêncio dos Inocentes', 'The Silence of the Lambs', 'DVD', 'Filme', 'Tak Fujimoto, Jonathan Demme', 'Clarice Starling é uma das melhores estudantes da academia de treinamento do FBI. Jack Crawford quer que Clarice entreviste o Dr. Hannibal Lecter, um psiquiatra brilhante e também um psicopata violento, que cumpre prisão perpétua por vários atos de assassinato e canibalismo. Crawford acredita que Lecter pode ter uma visão em um caso e que Starling, como uma mulher jovem e atraente, pode ser a isca para atraí-lo.', 'Jodie Foster, Anthony Hopkins, Scott Glenn, Ted Levine, Anthony Heald', 'Crime, Drama, Thriller', 'https://image.tmdb.org/t/p/w500/paGUSTwcFrAxpGV1hSQ2wsI28id.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1946, NULL, '2025-08-19 11:00:38.623', 1, 3, 6, 130, 8.272, 'Liberty Films', '', '', 'HD', '', '', 'en', 'A Felicidade Não Se Compra', 'It''s a Wonderful Life', 'VHS', 'Filme', 'Joseph F. Biroc, Joseph Walker, Frank Capra', 'Em Bedford Falls, no Natal, George Bailey, que sempre ajudou a todos, pensa em se suicidar saltando de uma ponte, em razão das maquinações de Henry Potter, o homem mais rico da região. Mas tantas pessoas oram por ele que Clarence, um anjo que espera há 220 anos para ganhar asas, é mandado à Terra para tentar fazer George mudar de ideia, mostrando sua importância para todos através de flashbacks.', 'James Stewart, Donna Reed, Lionel Barrymore, Thomas Mitchell, Henry Travers', 'Drama, Família, Fantasia', 'https://image.tmdb.org/t/p/w500/u9oQTcUTcWxJwv60JkGVjIBzfuB.jpg', 'L', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1995, NULL, '2025-08-19 11:01:02.640', 1, 3, 1, 127, 8.376, 'New Line Cinema', '', '', 'HD', '', '', 'en', 'Seven - Os Sete Crimes Capitais', 'Se7en', 'DVD', 'Filme', 'Darius Khondji, David Fincher', 'Quando, a ponto de se aposentar, o detetive William Somerset aborda o último caso com a ajuda do recém-transferido David Mills, eles descobrem uma série de assassinatos. Logo percebem que estão lidando com um assassino que tem como alvo pessoas que ele acredita representar os sete pecados capitais.', 'Morgan Freeman, Brad Pitt, Gwyneth Paltrow, John Cassini, Peter Crombie', 'Crime, Mistério, Thriller', 'https://image.tmdb.org/t/p/w500/cNFCNa5jUYmFmSpCg7dJ3jWd22d.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1977, NULL, '2025-08-19 11:02:03.652', 1, 3, 1, 121, 8.205, 'Lucasfilm Ltd.', '', '', 'HD', '', '', 'en', 'Guerra nas Estrelas', 'Star Wars', 'DVD', 'Filme', 'Gilbert Taylor, George Lucas', 'A princesa Leia é mantida refém pelas forças imperiais comandadas por Darth Vader. Luke Skywalker e Han Solo precisam libertá-la e restaurar a liberdade e a justiça na galáxia.', 'Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing, Alec Guinness', 'Aventura, Ação, Ficção científica', 'https://image.tmdb.org/t/p/w500/dw7X9YPjjAfIxKHW04V64Bb9TB0.jpg', '10', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2002, NULL, '2025-08-19 11:02:31.937', 1, 3, 2, 130, 8.429, 'O2 Filmes', '', '', 'HD', '', '', 'pt', 'Cidade de Deus', 'Cidade de Deus', 'Blu-ray', 'Filme', 'César Charlone, Fernando Meirelles', 'Buscapé é um jovem morador da Cidade de Deus que cresce em meio à violência. Com medo de se tornar um bandido, enxerga na fotografia uma oportunidade de ter uma vida digna.', 'Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen, Douglas Silva, Jonathan Haagensen', 'Drama, Crime', 'https://image.tmdb.org/t/p/w500/gfnXixcGC060QcG6JPxN6AMdVsq.jpg', '16', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1998, NULL, '2025-08-19 11:03:03.148', 1, 3, 1, 170, 8.22, 'DreamWorks Pictures', '', '', 'HD', '', '', 'en', 'O Resgate do Soldado Ryan', 'Saving Private Ryan', 'DVD', 'Filme', 'Steven Spielberg, Janusz Kamiński', 'Ao desembarcar na Normandia, no dia 6 de junho de 1944, o capitão Miller recebe a missão de comandar um grupo do segundo batalhão para o resgate do soldado James Ryan, caçula de quatro irmãos, dentre os quais três morreram em combate. Por ordens do chefe George C. Marshall, eles precisam procurar o soldado e garantir o seu retorno, com vida, para casa.', 'Tom Hanks, Tom Sizemore, Edward Burns, Barry Pepper, Adam Goldberg', 'Drama, História, Guerra', 'https://image.tmdb.org/t/p/w500/9SykLweWJJ5ISoT52s4Pfmul9DM.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1999, NULL, '2025-08-19 11:03:39.404', 1, 3, 2, 189, 8.503, 'Castle Rock Entertainment', '', '', 'HD', '', '', 'en', 'À Espera de um Milagre', 'The Green Mile', 'Blu-ray', 'Filme', 'Frank Darabont, David Tattersall', 'Milagres acontecem em lugares inesperados, mesmo no bloco de celas para o corredor da morte na Penitenciária Cold Mountain. Lá, John Coffey, um gentil e gigante prisioneiro com poderes sobrenaturais, traz um senso de espírito e humanidade aos seus guardas e colegas de cela.', 'Tom Hanks, David Morse, Bonnie Hunt, Michael Clarke Duncan, James Cromwell', 'Fantasia, Drama, Crime', 'https://image.tmdb.org/t/p/w500/14hEqW67IiHlKpzKMLUXyktzZIV.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1991, NULL, '2025-08-19 11:04:11.492', 1, 3, 2, 136, 8.129, 'Carolco Pictures', '', '', 'HD', '', '', 'en', 'O Exterminador do Futuro 2: O Julgamento Final', 'Terminator 2: Judgment Day', 'Blu-ray', 'Filme', 'Adam Greenberg, James Cameron', 'O jovem John Connor é a chave para a vitória da civilização sobre uma rebelião de robôs do futuro. No entanto, ele torna-se alvo de T-1000, um exterminador que pode assumir a forma que desejar e que foi enviado do futuro para matá-lo. Outro exterminador, o renovado T-800, também é enviado de volta ao passado para proteger o garoto. Quando John e sua mãe embarcam na fuga com T-800, o menino cria um vínculo forte e inesperado com o robô.', 'Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick, Earl Boen', 'Ação, Thriller, Ficção científica', 'https://image.tmdb.org/t/p/w500/nb0ertLALhkUqpmcahDFplqyc0I.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1985, NULL, '2025-08-19 11:04:35.170', 1, 3, 6, 115, 8.322, 'Universal Pictures', '', '', 'HD', '', '', 'en', 'De Volta para o Futuro', 'Back to the Future', 'VHS', 'Filme', 'Robert Zemeckis, Dean Cundey', 'Marty McFly, um típico adolescente americano dos anos 80, acidentalmente é enviado de volta ao ano de 1955 em um carro modificado para ser uma máquino do tempo, inventada por um cientista louco. Durante sua fantástica e maluca viagem no tempo, McFly tem que fazer com que seus futuros pais se encontrem e se apaixonem, para que assim ele possa ir de volta para o futuro.', 'Michael J. Fox, Christopher Lloyd, Crispin Glover, Lea Thompson, Claudia Wells', 'Aventura, Comédia, Ficção científica', 'https://image.tmdb.org/t/p/w500/JoAiVdWmz8XFA9rl43EtjT8ipn.jpg', 'L', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2001, NULL, '2025-08-19 11:07:26.368', 1, 3, 2, 126, 8.535, 'Studio Ghibli', '', '', 'HD', '', '', 'ja', 'A Viagem de Chihiro', '千と千尋の神隠し', 'Blu-ray', 'Filme', '奥井敦, Hayao Miyazaki', 'Chihiro e seus pais estão se mudando para uma cidade diferente. A caminho da nova casa, o pai decide pegar um atalho. Eles se deparam com uma mesa repleta de comida, embora ninguém esteja por perto. Chihiro sente o perigo, mas seus pais começam a comer. Quando anoitece, eles se transformam em porcos. Agora, apenas Chihiro pode salvá-los', 'Rumi Hiiragi, Miyu Irino, Mari Natsuki, Takashi Naitô, Yasuko Sawaguchi', 'Animação, Família, Fantasia', 'https://image.tmdb.org/t/p/w500/hhoKhsyJ3hFaxEm5pMdZRiTu2lJ.jpg', 'L', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1960, NULL, '2025-08-19 11:10:22.757', 1, 3, 6, 109, 8.422, 'Shamley Productions', '', '', 'HD', '', '', 'en', 'Psicose', 'Psycho', 'VHS', 'Filme', 'Alfred Hitchcock, John L. Russell', 'Marion Crane é uma secretária que rouba 40 mil dólares da imobiliária onde trabalha para se casar e começar uma nova vida. Durante a fuga à carro, ela enfrenta uma forte tempestade, erra o caminho e chega em um velho hotel. O estabelecimento é administrado por um sujeito atencioso chamado Norman Bates, que nutre um forte respeito e temor por sua mãe. Marion decide passar a noite no local, sem saber o perigo que a cerca.', 'Anthony Perkins, Janet Leigh, Vera Miles, John Gavin, Martin Balsam', 'Terror, Thriller, Mistério', 'https://image.tmdb.org/t/p/w500/oC2iYT2on8c2iZnehah1l6AWqGu.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1994, NULL, '2025-08-19 11:10:47.262', 1, 3, 1, 89, 8.257, 'Walt Disney Pictures', '', '', 'HD', '', '', 'en', 'O Rei Leão', 'The Lion King', 'DVD', 'Filme', 'Roger Allers, Rob Minkoff', 'Mufasa, o Rei Leão, e a rainha Sarabi apresentam ao reino o herdeiro do trono, Simba. O recém-nascido recebe a bênção do sábio babuíno Rafiki, mas ao crescer é envolvido nas artimanhas de seu tio Scar, o invejoso e maquiavélico irmão de Mufasa, que planeja livrar-se do sobrinho e herdar o trono.', 'Matthew Broderick, Moira Kelly, Nathan Lane, Ernie Sabella, James Earl Jones', 'Família, Animação, Drama, Fantasia, Aventura', 'https://image.tmdb.org/t/p/w500/8aIvm8OaJISOpVTt7rMIh7X35G5.jpg', '', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2006, NULL, '2025-08-19 11:13:12.324', 1, 3, 2, 151, 8.16, 'Warner Bros. Pictures', '', '', 'HD', '', '', 'en', 'Os Infiltrados', 'The Departed', 'Blu-ray', 'Filme', 'Martin Scorsese, Michael Ballhaus', 'Billy Costigan, um jovem policial, recebe a missão de se infiltrar na máfia, mais especificamente no grupo comandado por Frank Costello. Billy conquista sua confiança ao mesmo tempo em que Colin Sullivan, um criminoso que atuou na polícia como informante de Costello, também ascende dentro da corporação. Tanto Billy quanto Colin se sentem aflitos devido à vida dupla que levam. Mas quando a máfia e a polícia descobrem que há um espião entre eles, a vida de ambos passa a correr perigo.', 'Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg, Martin Sheen', 'Drama, Thriller, Crime', 'https://image.tmdb.org/t/p/w500/5ahf025FzL64EuqUOwM4PB598eb.jpg', '', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1988, NULL, '2025-08-19 11:13:46.905', 1, 3, 6, 88, 8.45, 'Studio Ghibli', '', '', 'HD', '', '', 'ja', 'O Túmulo dos Vagalumes', '火垂るの墓', 'VHS', 'Filme', '高畑勲, Nobuo Koyama', 'O filme relata a história de dois irmãos, Seita e Setsuko, no período da Segunda Guerra Mundial no Japão. O pai deles é convocado para defender o país na guerra, pois faz parte da marinha japonesa e a mãe falece em um bombardeio de aviões norte-americanos. A partir daí, o filme mostra a luta pela sobrevivência das duas crianças em meio à pobreza e miséria que assola o país. Fome, doenças e a falta de generosidade e sensibilidade dos adultos faz deste percurso um dos filmes mais bonitos e comoventes sobre o trágico quadro gerado pela guerra.', '辰巳努, 白石綾乃, 志乃原良子, 山口朱美, Masayo Sakai', 'Animação, Drama, Guerra', 'https://image.tmdb.org/t/p/w500/kHFUyxNJfhMkKk1FwrNHd62KTEs.jpg', '', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1998, NULL, '2025-08-19 11:14:31.146', 1, 3, 1, 119, 8.335, 'New Line Cinema', '', '', 'HD', '', '', 'en', 'A Outra História Americana', 'American History X', 'DVD', 'Filme', 'Tony Kaye, Tony Kaye', 'Derek busca vazão para suas agruras tornando-se líder de uma gangue de racistas. A violência o leva a um assassinato, e ele é condenado pelo crime. Três anos mais tarde, ele sai da prisão e tem que convencer seu irmão, que está prestes a assumir a liderança do grupo, a não trilhar o mesmo caminho.', 'Edward Norton, Edward Furlong, Beverly D''Angelo, Jennifer Lien, Ethan Suplee', 'Drama', 'https://image.tmdb.org/t/p/w500/nFou7IjLzU0cGC3iVwm2vYWZtGx.jpg', '16', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1994, NULL, '2025-08-19 11:14:57.397', 1, 3, 2, 111, 8.301, 'Gaumont', '', '', 'HD', '', '', 'fr', 'O Profissional', 'Léon', 'Blu-ray', 'Filme', 'Thierry Arbogast, Luc Besson', 'Mathilda tem apenas 12 anos de idade mas já conhece o lado obscuro da vida: seu pai abusivo guarda drogas para policiais corruptos e a mãe a negligencia. O vizinho Léon gosta de cuidar de plantas, mas é um assassino de aluguel para o gângster Tony. Quando sua família é assassinada por um agente antidrogas desonesto, Mathilda se une a um relutante Léon para aprender o negócio mortal e vingar a morte da família.', 'Jean Reno, Natalie Portman, Gary Oldman, Danny Aiello, Peter Appel', 'Crime, Drama, Ação', 'https://image.tmdb.org/t/p/w500/lNyuX5XibtzRImuhACGy42jHXIs.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1995, NULL, '2025-08-19 11:15:27.681', 1, 3, 1, 106, 8.173, 'Bad Hat Harry Productions', '', '', 'HD', '', '', 'en', 'Os Suspeitos', 'The Usual Suspects', 'DVD', 'Filme', 'Newton Thomas Sigel, Bryan Singer', 'Um detetive interroga um dos únicos sobreviventes de uma explosão no cais que provocou dezenas de mortes. O suspeito conta uma história sobre os eventos que levaram ele e mais quatro criminosos ao local do crime, deixando dúvidas sobre a verdade.', 'Stephen Baldwin, Gabriel Byrne, Benicio del Toro, Kevin Pollak, Kevin Spacey', 'Drama, Crime, Thriller', 'https://image.tmdb.org/t/p/w500/ueAOi0aESiXufglEj5011sfFp0e.jpg', '16', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1962, NULL, '2025-08-19 11:15:52.170', 1, 3, 6, 135, 8.43, 'Shochiku', '', '', 'HD', '', '', 'ja', 'Harakiri', '切腹', 'VHS', 'Filme', 'Masaki Kobayashi, 宮島義勇', 'No século 18, o Japão não está mais em guerra e o país é governado com firmeza. Hanshiro Tsugumo, um dos muitos ronin (samurais errantes) desempregados, decide bater à porta do poderoso clã Ii. Recebido por Kageyu Saito, o intendente do clã, ele pede permissão para cometer suicídio por harakiri na residência. Tentando dissuadi-lo, Saito começa a lhe contar a história de Motome Chijiwa, outro ronin que também queria realizar o mesmo ritual no local.', 'Tatsuya Nakadai, 石濱朗, 岩下志麻, 丹波哲郎, 三島雅夫', 'Ação, Drama, História', 'https://image.tmdb.org/t/p/w500/5konZnIbcAxZjP616Cz5o9bKEfW.jpg', '', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1936, NULL, '2025-08-19 11:16:10.866', 1, 3, 6, 87, 8.281, 'Charles Chaplin Productions', '', '', 'HD', '', '', 'en', 'Tempos Modernos', 'Modern Times', 'VHS', 'Filme', 'Charlie Chaplin, Ira H. Morgan, Roland Totheroh, Bud Thackery', 'Sujeito ao ritmo de produção infernal da fábrica, o Vagabundo tem um súbito colapso nervoso. Do hospital, ele vai para a prisão e fica desempregado, sempre cercado pela industrialização moderna. Certo dia, ele se depara com uma menina órfã.', 'Charlie Chaplin, Paulette Goddard, Henry Bergman, Tiny Sandford, Chester Conklin', 'Comédia, Drama, Romance', 'https://image.tmdb.org/t/p/w500/rKepEXpgdowaIFbVcGIHmZ2H20J.jpg', 'L', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2006, NULL, '2025-08-19 11:16:37.689', 1, 3, 2, 130, 8.204, 'Warner Bros. Pictures', '', '', 'HD', '', '', 'en', 'O Grande Truque', 'The Prestige', 'Blu-ray', 'Filme', 'Wally Pfister, Christopher Nolan', 'No século 19, em Londres, dois amigos ilusionistas e mágicos, Alfred Borden e Rupert Angier, acabam construindo uma rivalidade, uma batalha por supremacia, que se estende ao longo dos anos e que se transforma em obsessão, cujos resultados serão inevitavelmente trágicos.', 'Hugh Jackman, Christian Bale, Michael Caine, Piper Perabo, Rebecca Hall', 'Drama, Mistério, Ficção científica', 'https://image.tmdb.org/t/p/w500/9yOIPXWQ9ttsZfzHvmcS7XiV8To.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2011, NULL, '2025-08-19 11:17:17.245', 1, 3, 2, 112, 8.272, 'Gaumont', '', '', 'HD', '', '', 'fr', 'Intocáveis', 'Intouchables', 'Blu-ray', 'Filme', 'Éric Toledano, Olivier Nakache, Mathieu Vadepied', 'Quando um ex-presidiário é contratado para cuidar de um aristocrata francês, seu novo trabalho se torna uma aventura imprevisível. Acelerar uma Maserati em Paris, seduzir mulheres, e fazer parapente sobre os Alpes é apenas o começo, pois ele vira o mundo da classe alta de Paris de cabeça para baixo.', 'François Cluzet, Omar Sy, Anne Le Ny, Audrey Fleurot, Joséphine de Meaux', 'Drama, Comédia', 'https://image.tmdb.org/t/p/w500/2tAzFC2xUAXEx96l5Xixb6WLAyO.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1968, NULL, '2025-08-19 11:17:37.868', 1, 3, 6, 166, 8.281, 'Paramount Pictures', '', '', 'HD', '', '', 'it', 'Era uma Vez no Oeste', 'C''era una volta il West', 'VHS', 'Filme', 'Tonino Delli Colli, Sergio Leone', 'Enquanto os construtores ferroviários marcham imparavelmente através do deserto de Arizona a caminho do mar, Jill chega à pequena cidade de Flagstone com a intenção de começar uma nova vida.', 'Claudia Cardinale, Henry Fonda, Jason Robards, Charles Bronson, Gabriele Ferzetti', 'Drama, Faroeste', 'https://image.tmdb.org/t/p/w500/zaCMbBMT9v3lGBXT4RAOkWqpb4h.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1943, NULL, '2025-08-19 11:18:23.785', 1, 3, 6, 102, 8.156, 'Warner Bros. Pictures', '', '', 'HD', '', '', 'en', 'Casablanca', 'Casablanca', 'VHS', 'Filme', 'Michael Curtiz, Arthur Edeson', 'Durante a Segunda Guerra Mundial, muitos fugitivos tentavam escapar dos nazistas por uma rota que passava pela cidade de Casablanca. O exilado americano Rick Blaine encontrou refúgio na cidade, dirigindo uma das principais casas noturnas da região. Clandestinamente, tentando despistar o Capitão Renault, ele ajuda refugiados, possibilitando que eles fujam para os Estados Unidos. Quando um casal pede sua ajuda para deixar o país, ele reencontra uma grande paixão do passado, a bela Ilsa. Este amor vai encontrar uma nova vida e eles vão lutar para fugir juntos.', 'Humphrey Bogart, Ingrid Bergman, Paul Henreid, Claude Rains, Conrad Veidt', 'Drama, Romance', 'https://image.tmdb.org/t/p/w500/oyGRZVIthHJjc98ekKpeWpDh8Ws.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1987, NULL, '2025-08-19 11:21:08.129', 1, 3, 2, 102, 7.347, 'Orion Pictures', '', '', 'HD', '', '', 'en', 'RoboCop - O Policial do Futuro', 'RoboCop', 'Blu-ray', 'Filme', 'Paul Verhoeven, Jost Vacano', 'Em uma Detroit violenta e quase apocalíptica, a malvada corporação Omni Consumer Products (OCP) ganha um contrato do governo municipal para privatizar a força policial. Para testar seus ciborgues de erradicação do crime, a empresa leva o policial de rua Alex Murphy a um confronto armado com o senhor do crime Boddicker para que eles possam usar seu corpo para apoiar seu protótipo não testado do RoboCop. Mas quando RoboCop descobre os planos nefastos da empresa, ele se volta contra seus mestres.', 'Peter Weller, Nancy Allen, Dan O''Herlihy, Ronny Cox, Kurtwood Smith', 'Ação, Thriller, Ficção científica', 'https://image.tmdb.org/t/p/w500/uZ27cWusfoGFh7sOiUsIENxW48S.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1988, NULL, '2025-08-19 11:21:29.136', 1, 3, 1, 86, 7.26, 'Paramount Pictures', '', '', 'HD', '', '', 'en', 'Corra que a Polícia Vem Aí!', 'The Naked Gun: From the Files of Police Squad!', 'DVD', 'Filme', 'David Zucker, Robert M. Stevens', 'Leslie Nielsen interpreta o tira cabeça-dura Frank Debrin, que tenta acabar com um brilhante plano para assassinar a Rainha Elizabeth. Priscilla Presley, O.J. Simpson, um castor empalhado, dois times de baseball e uma curiosa variedade de piadas e situações hilariantes farão seu medidor de risadas estourar.', 'Leslie Nielsen, Priscilla Presley, Ricardo Montalban, George Kennedy, O. J. Simpson', 'Comédia, Crime', 'https://image.tmdb.org/t/p/w500/iYCWSKbC4fwzaKEJ9QFx8MsH7bJ.jpg', 'L', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2014, NULL, '2025-08-19 11:21:45.712', 1, 3, 2, 169, 8.459, 'Legendary Pictures', '', '', 'HD', '', '', 'en', 'Interestelar', 'Interstellar', 'Blu-ray', 'Filme', 'Hoyte van Hoytema, Christopher Nolan', 'As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand, Jenkins e Doyle, ele seguirá em busca de um novo lar.', 'Matthew McConaughey, Anne Hathaway, Michael Caine, Jessica Chastain, Casey Affleck', 'Aventura, Drama, Ficção científica', 'https://image.tmdb.org/t/p/w500/nCbkOyOMTEwlEV0LtCOvCnwEONA.jpg', '10', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1970, NULL, '2025-08-19 11:21:56.854', 1, 3, 2, 92, 6.4, 'Terra-Filmkunst', '', '', 'HD', '', '', 'de', 'Eram Os Deuses Astronautas?', 'Erinnerungen an die Zukunft', 'Blu-ray', 'Filme', 'Harald Reinl, Ernst Wild', 'Documentário baseado no livro de Erich Von Daniken sobre os antigos mistérios do mundo, como as pirâmides do Egito e do México, os antigos desenhos de cavernas, os monumentos da Ilha de Páscoa, etc., e o fato de que essas coisas e a civilização moderna poderiam ter sido influenciado por visitas extraterrestres, centenas (ou talvez milhares) de anos atrás.', 'Heinz-Detlev Bock, Klaus Kindler, Christian Marschall, Erich von Däniken, Aleksandr Kazantsev', 'Documentário, Mistério', 'https://image.tmdb.org/t/p/w500/yzF1RNZo1OQtutGrYpFCx2yyXzD.jpg', '', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2002, NULL, '2025-08-19 11:07:49.573', 1, 3, 2, 150, 8.38, 'Bac Films', '', '', 'HD', '', '', 'en', 'O Pianista', 'The Pianist', 'Blu-ray', 'Filme', 'Roman Polanski, Paweł Edelman', 'Um pianista judeu polonês vê Varsóvia mudar gradualmente à medida que a Segunda Guerra Mundial começa. Szpilman é forçado a ir para o Gueto de Varsóvia, mas depois é separado de sua família durante a Operação Reinhard. A partir deste momento até que os prisioneiros dos campos de concentração sejam liberados, Szpilman se esconde em vários locais entre as ruínas de Varsóvia.', 'Adrien Brody, Thomas Kretschmann, Frank Finlay, Maureen Lipman, Emilia Fox', 'Drama, Guerra', 'https://image.tmdb.org/t/p/w500/zgtCY3VshbIv3UfNkdvVEShGmlE.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2000, NULL, '2025-08-19 11:08:19.015', 1, 3, 2, 155, 8.221, 'Universal Pictures', '', '', 'HD', '', '', 'en', 'Gladiador', 'Gladiator', 'Blu-ray', 'Filme', 'Ridley Scott, John Mathieson', 'Nos dias finais do reinado de Marcus Aurelius, o imperador desperta a ira de seu filho Commodus ao tornar pública sua predileção em deixar o trono para Maximus, o comandante do exército romano. Sedento pelo poder, Commodus mata seu pai, assume a coroa e ordena a morte de Maximus, que consegue fugir antes de ser pego e passa a se esconder sob a identidade de um escravo e gladiador do Império Romano.', 'Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed, Richard Harris', 'Ação, Drama, Aventura', 'https://image.tmdb.org/t/p/w500/R1ieKOdGHYL7BRpl0iRgNV1uXw.jpg', '14', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2019, NULL, '2025-08-19 11:09:57.703', 1, 3, 2, 132, 8.498, 'Barunson E&A', '', '', 'HD', '', '', 'ko', 'Parasita', '기생충', 'Blu-ray', 'Filme', '홍경표, Bong Joon-Ho', 'Toda a família de Ki-taek está desempregada, vivendo num porão sujo e apertado. Uma obra do acaso faz com que o filho adolescente da família comece a dar aulas de inglês à garota de uma família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe, filho e filha bolam um plano para se infiltrarem também na família glamorosa, um a um. No entanto, os segredos e mentiras necessários à ascensão social custarão caro a todos.', 'Kang-ho Song, Sun-kyun Lee, Yeo-Jeong Cho, Woo-sik Choi, So-dam Park', 'Comédia, Thriller, Drama', 'https://image.tmdb.org/t/p/w500/bik2BZjmVjeE6LOZqtuTjb4jJPQ.jpg', '16', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2014, NULL, '2025-08-19 11:14:10.481', 1, 3, 2, 107, 8.4, 'Bold Films', '', '', 'HD', '', '', 'en', 'Whiplash: Em Busca da Perfeição', 'Whiplash', 'Blu-ray', 'Filme', 'Sharone Meir, Damien Chazelle', 'Andrew sonha em ser o melhor baterista de sua geração. Ele chama a atenção do impiedoso mestre do jazz Terence Fletcher, que ultrapassa os limites e transforma seu sonho em uma obsessão, colocando em risco a saúde física e mental do jovem músico.', 'Miles Teller, J.K. Simmons, Paul Reiser, Melissa Benoist, Austin Stowell', 'Drama, Música', 'https://image.tmdb.org/t/p/w500/dtnzzmGOy2Ni89Ir4I1FTO40FJQ.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2025, NULL, '2025-08-19 11:19:56.123', 1, 3, 2, 160, NULL, 'RadicalMedia', '', '', 'HD', '', '', 'en', 'Hamilton', 'Hamilton', 'Blu-ray', 'Filme', 'Thomas Kail, Declan Quinn', 'Hamilton é um musical que conta a história da América por vozes americanas. Por meio da história de um dos principais fundadores americanos e primeiro secretário do Tesouro, Alexander Hamilton, a trilha sonora que mistura hip-hop, jazz, R&B e Broadway revoluciona o teatro no The Richard Rodgers Theatre, na Broadway, em junho de 2016.', 'Lin-Manuel Miranda, Leslie Odom Jr., Renée Elise Goldsberry, Phillipa Soo, Daveed Diggs', 'História, Drama', 'https://image.tmdb.org/t/p/w500/h1B7tW0t399VDjAcWJh8m87469b.jpg', '', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(1997, NULL, '2025-08-19 11:20:43.093', 1, 3, 1, 194, 7.9, 'Paramount Pictures', '', '', 'HD', '', '', 'en', 'Titanic', 'Titanic', 'DVD', 'Filme', 'Russell Carpenter, James Cameron', 'Um artista pobre e uma jovem rica se conhecem e se apaixonam na fatídica jornada do Titanic, em 1912. Embora esteja noiva do arrogante herdeiro de uma siderúrgica, a jovem desafia sua família e amigos em busca do verdadeiro amor.', 'Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates, Frances Fisher', 'Drama, Romance', 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', '12', '', '', '');
INSERT INTO public.midia
(ano_lancamento, atualizado_em, criado_em, quantidade_itens, cadastro_id, midia_tipo_id, duracao, nota_media, estudio, faixas, formato_audio, formato_video, numero_serie, observacoes, linguagem, titulo_alternativo, titulo_original, midia_tipo_nome, formato_midia, diretores, sinopse, artistas, generos, capa_url, classificacao_etaria, colecao, temporada, edicao)
VALUES(2009, NULL, '2025-08-19 11:20:56.188', 1, 3, 2, 177, 7.592, 'Dune Entertainment', '', '', 'HD', '', '', 'en', 'Avatar', 'Avatar', 'Blu-ray', 'Filme', 'James Cameron, Mauro Fiore', 'Apesar de não ter mais os movimentos da perna, o ex-fuzileiro naval Jake Sully ainda sente que pode ser um guerreiro. Sua intuição começa a se tornar realidade quando ele viaja anos-luz até a estação espacial montada no Planeta Pandora. Habitado por grandes seres azuis, os Na´vi, o local tem uma atmosfera fatal para qualquer terrestre. Por isso, oficiais criaram o programa Avatar, em que um corpo biológico, híbrido de humano e Na´vi, pode ser comandado a distância.', 'Sam Worthington, Zoe Saldaña, Sigourney Weaver, Stephen Lang, Michelle Rodriguez', 'Ação, Aventura, Fantasia, Ficção científica', 'https://image.tmdb.org/t/p/w500/iNMP8uzV2Ing6ZCw0IICgEFVNfC.jpg', '10', '', '', '');