-- Hobbies padrão
INSERT INTO hobby (nome, descricao) VALUES
  ('Leitura', 'Apreciar livros, revistas ou quadrinhos para entretenimento ou aprendizado.'),
  ('Escrita', 'Produzir textos como contos, poesias, blogs ou diários pessoais.'),
  ('Desenho', 'Criar imagens artísticas à mão com lápis, caneta ou carvão.'),
  ('Pintura', 'Utilizar tintas para expressar criatividade em telas ou outras superfícies.'),
  ('Fotografia', 'Capturar momentos e paisagens por meio de câmeras digitais ou analógicas.'),
  ('Jardinagem', 'Cuidar de plantas, flores e hortas para relaxamento e conexão com a natureza.'),
  ('Culinária', 'Preparar receitas variadas como forma de lazer e descoberta de sabores.'),
  ('Costura', 'Criar ou reparar roupas e acessórios usando agulha e linha.'),
  ('Artesanato', 'Produzir objetos manuais decorativos ou funcionais com diferentes materiais.'),
  ('Colecionismo', 'Juntar e organizar itens como moedas, selos, quadrinhos ou action figures.'),
  ('Tocar Instrumento', 'Aprender e praticar instrumentos como violão, teclado ou bateria.'),
  ('Cantar', 'Praticar canto como forma de expressão artística e emocional.'),
  ('Dança', 'Movimentar-se com ritmo, seja por lazer ou como atividade física.'),
  ('Meditação', 'Praticar técnicas de atenção plena para reduzir o estresse e melhorar o foco.'),
  ('Yoga', 'Realizar posturas e exercícios de respiração para bem-estar físico e mental.'),
  ('Caminhada', 'Caminhar em ritmo leve ou moderado como forma de lazer e exercício.'),
  ('Corrida', 'Praticar corrida para manter a saúde e desafiar seus limites físicos.'),
  ('Andar de Bicicleta', 'Pedalar em trilhas, ruas ou parques por lazer ou exercício.'),
  ('Natação', 'Nadar em piscinas ou em águas naturais como forma de recreação e saúde.'),
  ('Esportes em Equipe', 'Participar de jogos coletivos como futebol, vôlei ou basquete.'),
  ('Video Game', 'Jogar jogos digitais em consoles ou computadores para entretenimento.'),
  ('RPG de Mesa', 'Participar de jogos de interpretação de personagens com dados e narrativa.'),
  ('Modelismo', 'Montar e pintar miniaturas de aviões, carros, trens ou cenários.'),
  ('Programação', 'Criar aplicativos, jogos ou sistemas por diversão ou aprendizado.'),
  ('Aprender Idiomas', 'Estudar novas línguas como forma de se comunicar e expandir horizontes.'),
  ('Assistir Filmes e Séries', 'Apreciar produções cinematográficas como forma de lazer.'),
  ('Pesca', 'Atividade relaxante praticada em rios, lagos ou no mar.'),
  ('Acampamento', 'Passar tempo na natureza, geralmente dormindo em barracas ou cabanas.'),
  ('Astronomia', 'Observar estrelas, planetas e fenômenos celestes com telescópios ou a olho nu.'),
  ('Voluntariado', 'Participar de ações sociais e comunitárias como forma de ajudar os outros.')
ON CONFLICT (nome) DO UPDATE
SET descricao = EXCLUDED.descricao;

-- Tipos de mídia com campo 'ativo'
INSERT INTO midia_tipo (nome, descricao, ativo) VALUES
  ('DVD', 'Disco digital usado para filmes, shows e conteúdos multimídia.', TRUE),
  ('Blu-ray', 'Disco de alta definição usado para filmes e jogos.', TRUE),
  ('CD', 'Disco compacto usado para músicas, softwares ou dados.', FALSE),
  ('Vinil', 'Disco de vinil usado para músicas com qualidade analógica.', FALSE),
  ('K7 (Fita Cassete)', 'Mídia analógica magnética para gravação de áudio.', FALSE),
  ('VHS', 'Fita de vídeo analógica usada para gravação e reprodução de filmes.', TRUE),
  ('LaserDisc', 'Disco óptico usado antes do DVD, geralmente em formato grande.', FALSE),
  ('Digital (Arquivos)', 'Coleções digitais como MP3, FLAC, vídeos ou livros digitais.', FALSE),
  ('Jogo Físico (Console)', 'Mídias físicas como cartuchos ou discos para consoles de videogame.', FALSE),
  ('Jogo de PC (CD/DVD)', 'Jogos de computador distribuídos em CD, DVD ou mídia física.', FALSE),
  ('Cartucho de Videogame', 'Cartuchos de jogos clássicos (NES, SNES, Mega Drive etc).', FALSE),
  ('Livro Físico', 'Livros impressos colecionáveis (literatura, mangás, quadrinhos).', FALSE),
  ('Revista/Quadrinhos', 'Coleções de revistas, HQs, mangás ou fanzines.', FALSE),
  ('Cédula', 'Dinheiro em papel de diferentes países e épocas.', FALSE),
  ('Moeda', 'Moedas metálicas antigas ou comemorativas.', FALSE),
  ('Cartões (Trading Cards)', 'Cartões colecionáveis (Pokémon, Magic, Yu-Gi-Oh!, etc).', FALSE),
  ('Miniaturas/Estatuetas', 'Peças decorativas de personagens, séries ou temas específicos.', FALSE),
  ('Pôster', 'Pôsteres decorativos ou promocionais de filmes, bandas, etc.', FALSE),
  ('Figurinha (Álbum)', 'Figurinhas colecionáveis de álbuns temáticos (futebol, séries etc).', FALSE),
  ('Colecionável Digital (NFT)', 'Itens digitais únicos baseados em blockchain.', FALSE)
ON CONFLICT (nome) DO UPDATE
SET descricao = EXCLUDED.descricao,
    ativo = EXCLUDED.ativo;
