ALTER TABLE midia
  ALTER COLUMN sinopse TYPE VARCHAR(2000),
  ALTER COLUMN observacoes TYPE VARCHAR(1000),
  ALTER COLUMN generos TYPE VARCHAR(500),
  ALTER COLUMN artistas TYPE VARCHAR(500),
  ALTER COLUMN diretores TYPE VARCHAR(500),
  ALTER COLUMN capa_url TYPE VARCHAR(500);
